//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulesTable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulesTable.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows minimum count is 3 pcs..
        /// </summary>
        public static string Error3Row {
            get {
                return ResourceManager.GetString("Error3Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your schedule is not a Schedules table. Please use WEANDREVIT template..
        /// </summary>
        public static string ErrorIncorrectSchedule {
            get {
                return ResourceManager.GetString("ErrorIncorrectSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A schedules table is not placed on a first sheet..
        /// </summary>
        public static string ErrorNoScheduleOnFirstSheet {
            get {
                return ResourceManager.GetString("ErrorNoScheduleOnFirstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules are not found! Please set Name for schedules as following: STR_Slab_*Slab rebar schedule*. A text bettwen * symbols will be shown in a schedules table..
        /// </summary>
        public static string ErrorNoSchedulesFound {
            get {
                return ResourceManager.GetString("ErrorNoSchedulesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sheet complect parameter is empty.
        /// </summary>
        public static string ErrorNoSheetComplect {
            get {
                return ResourceManager.GetString("ErrorNoSheetComplect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedules table is placed on several sheets! Failes to define a sheet set.
        /// </summary>
        public static string ErrorTwoSheets {
            get {
                return ResourceManager.GetString("ErrorTwoSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a schedules table or select it on a sheet.
        /// </summary>
        public static string MsgSelectOrOpen {
            get {
                return ResourceManager.GetString("MsgSelectOrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a schedules table on a sheet.
        /// </summary>
        public static string MsgSelectSchedule {
            get {
                return ResourceManager.GetString("MsgSelectSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADSK_SheetNumber.
        /// </summary>
        public static string ParameterSheetNumber {
            get {
                return ResourceManager.GetString("ParameterSheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mng.SheetComplect.
        /// </summary>
        public static string ParameterSheetSet {
            get {
                return ResourceManager.GetString("ParameterSheetSet", resourceCulture);
            }
        }
    }
}
